# action.yml
name: 'Vulcan'
description: 'Auto fix on the branch which triggers a workflow'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  path:
    description: 'Checkout directory name'
    default: 'target'
  
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - -e "TOKEN=${{ inputs.token }}"
    - -e "VULCAN_TARGET=${{ inputs.path }}"
