# action.yml
name: 'Vulcan'
description: 'Auto fix on the branch which triggers a workflow'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TOKEN: ${{ inputs.token }}
