# /vulcan/github_cli/create-issue.sh
#!/bin/bash

# exist dependency
wget -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux32 -O /jq && chmod +x /jq

VULCAN_ISSUE_FL_CONTENTS=""
VULCAN_TRIGGER_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/blob/$GITHUB_SHA"
for i in {0..4}
do
	ithFL=$(sh -c "cat $VULCAN_OUTPUT_DIR/fl.json | /jq '.[$i]'")
	buggy_source=$(echo $ithFL | /jq -r '.[0]')
    # buggy_source=${buggy_source##*\")}
    buggy_line=$(echo $ithFL | /jq '.[1]')
    buggy_score=$(echo $ithFL | /jq '.[2]')
    
    if [ ! -z "$VULCAN_ISSUE_FL_CONTENTS" ]; then
        VULCAN_ISSUE_FL_CONTENTS="$VULCAN_ISSUE_FL_CONTENTS----"
    fi
    VULCAN_ISSUE_FL_CONTENTS="$VULCAN_ISSUE_FL_CONTENTS\n$VULCAN_TRIGGER_URL/$buggy_source#L$buggy_line\n"
done

echo ==========Creating Issue==========
COMMAND="gh issue create \
-t \"Vulcan\" \
-b \"This issue is generated by Vulcan for commit: $GITHUB_SHA
Fault Localization Result:
$VULCAN_ISSUE_FL_CONTENTS\" \
|| true"
echo $COMMAND
EXECUTE_ISSUE_COMMAND=$(sh -c "$COMMAND")
echo $EXECUTE_ISSUE_COMMAND
echo ==================================
