# /vulcan/github_cli/create-issue.sh
#!/bin/bash

_write_1st_fl_info() {
	ithFL=$(sh -c "$GITHUB_ACTION_PATH/jq '.[0]' $VULCAN_OUTPUT_DIR/fl_sortby_score.json")
	buggy_source=$(echo $ithFL | $GITHUB_ACTION_PATH/jq -r '.[0]')
	buggy_line=$(echo $ithFL | $GITHUB_ACTION_PATH/jq '.[1]')
	buggy_score=$(echo $ithFL | $GITHUB_ACTION_PATH/jq '.[2]')

    VULCAN_ISSUE_BODY=$( \
        printf "$VULCAN_ISSUE_BODY\n\n----\n%s\n- [ ] %s\n%s/%s#L%d\n%s" \
        "Clicking on the link, you take the page with code highlighted." \
        "Here is most suspicious code piece." \
        $VULCAN_TRIGGER_URL \
        $buggy_source \
        $buggy_line \
        "Recommend debugging here.\nClick below the collapsed section for more FL information." \
    )
}

_open_collapsed_section() {
	VULCAN_ISSUE_BODY=$(printf "$VULCAN_ISSUE_BODY\n\n<details><summary>Click here for more FL</summary>")
}

_close_collapsed_section() {
	VULCAN_ISSUE_BODY=$(printf "$VULCAN_ISSUE_BODY\n\n</details>")
}

_write_basic_fl_info() {
	_write_1st_fl_info
	_open_collapsed_section
	for i in {1..4}
	do
		ithFL=$(sh -c "$GITHUB_ACTION_PATH/jq '.[$i]' $VULCAN_OUTPUT_DIR/fl_sortby_score.json")
		buggy_source=$(echo $ithFL | $GITHUB_ACTION_PATH/jq -r '.[0]')
		buggy_line=$(echo $ithFL | $GITHUB_ACTION_PATH/jq '.[1]')
		buggy_score=$(echo $ithFL | $GITHUB_ACTION_PATH/jq '.[2]')
		
		if [ "$buggy_source" = "null" ]; then
			break
		fi
		
		VULCAN_ISSUE_BODY=$( \
			printf "$VULCAN_ISSUE_BODY\n\n----\n- [ ] Suspicious score: %.2f %s/%s#L%d" \
			$buggy_score \
			$VULCAN_TRIGGER_URL \
			$buggy_source \
			$buggy_line \
		)
	done
	_close_collapsed_section
}

_write_5_more_equal_fl_info() {
	VULCAN_ISSUE_BODY=$( \
		printf "$VULCAN_ISSUE_BODY\n\n----\n%s\n%s\n%s" \
		"Clicking on the link, you take the page with code highlighted." \
		"There are a lot of the suspicious code snippets and show 5 among them." \
		"Recommend that split your tests or adde new tests." \
	)
	for i in {0..4}
	do
		ithFL=$(sh -c "$GITHUB_ACTION_PATH/jq '.[$i]' $VULCAN_OUTPUT_DIR/fl_sortby_score.json")
		buggy_source=$(echo $ithFL | $GITHUB_ACTION_PATH/jq -r '.[0]')
		buggy_line=$(echo $ithFL | $GITHUB_ACTION_PATH/jq '.[1]')
		buggy_score=$(echo $ithFL | $GITHUB_ACTION_PATH/jq '.[2]')
		
		if [ "$buggy_source" = "null" ]; then
			break
		fi
		
		VULCAN_ISSUE_BODY=$( \
			printf "$VULCAN_ISSUE_BODY\n\n----\nSuspicious score: %.2f %s/%s#L%d" \
			$buggy_score \
			$VULCAN_TRIGGER_URL \
			$buggy_source \
			$buggy_line \
		)
	done
}

_write_fl_info() {
	VULCAN_ISSUE_HEADER="Top 5 fault localization results"
	VULCAN_ISSUE_BODY=$(printf "$VULCAN_ISSUE_INTRO\n$VULCAN_ISSUE_HEADER\n")
	VULCAN_TRIGGER_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/blob/$GITHUB_SHA"
	$GITHUB_ACTION_PATH/jq 'sort_by(.[2]) | reverse' $VULCAN_OUTPUT_DIR/fl.json > $VULCAN_OUTPUT_DIR/fl_sortby_score.json
	
	is_more_than_top5=$($GITHUB_ACTION_PATH/jq 'group_by(.[2])' $VULCAN_OUTPUT_DIR/fl_sortby_score.json | $GITHUB_ACTION_PATH/jq '.[1]')
	
	if [ "$is_more_than_top5" = "null" ];
	then
		_write_5_more_equal_fl_info
	else
		_write_basic_fl_info
	fi
}

_write_patch_info() {
	VULCAN_ISSUE_HEADER="Patch informations"
	VULCAN_ISSUE_BODY=$(printf "$VULCAN_ISSUE_INTRO\n$VULCAN_ISSUE_HEADER\n")
	BLOCK="\x60\x60\x60"
	for diff_file in $(sh -c "ls $PATCH_OUTPUT_PATH/*.diff")
	do
		VULCAN_ISSUE_BODY=$( \
			printf "$VULCAN_ISSUE_BODY\n\n----\n$BLOCK c\n$(cat $diff_file)\n$BLOCK"
		)
	done
}

_create_issue() {
	echo ==========Creating Issue==========
	VULCAN_ISSUE_CREATE_RESULT=$(\
		gh issue create \
		-t "Vulcan" \
		-a "$GITHUB_ACTOR" \
		-b "$VULCAN_ISSUE_BODY" \
	)
	printf "$VULCAN_ISSUE_CREATE_RESULT\n"
	echo ==================================
}

# exist dependency
wget -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux32 -O $GITHUB_ACTION_PATH/jq && chmod +x $GITHUB_ACTION_PATH/jq

VULCAN_ISSUE_INTRO="This issue is generated by Vulcan for commit: $GITHUB_SHA"
if [ -f $PATCH_OUTPUT_PATH/*-0001-*.diff ];
then
	_write_patch_info
else
	_write_fl_info
fi
_create_issue
