# /vulcan/github_cli/create-issue.sh
#!/bin/bash

echo ==========Creating Issue==========
COMMAND="gh issue create \
-t \"Vulcan\" \
-b \"This issue is generated by Vulcan for commit: $GITHUB_SHA
Fault Localization Result:
$(cat $VULCAN_OUTPUT_DIR/fl.output)\" \
|| true"
echo $COMMAND
EXECUTE_ISSUE_COMMAND=$(sh -c "$COMMAND")
echo $EXECUTE_ISSUE_COMMAND
echo ==================================
